# to delete unimportant files generated by tex
import os

dir = "./"
files = os.listdir(dir)

for file in files:
    if os.path.isfile(file) and not file.endswith(".tex") and not file.endswith(".pdf") and not file.endswith(".cls") and not file.endswith(".sty") and not file.endswith(".py") and not file.endswith(".md") and not file.endswith(".gitignore"):
        os.remove(os.path.join(dir,file))